//ACÁ CREO UN CONTENEDOR QUE VA A TENER MÉTODOS CON NOMBRES DISTINTOS, PERO QUE APLIQUEN LOS MÉTODOS DEL ContenedorArchivo.
//ESTE DAO VA A SER LLAMADO DESDE EL ROUTER PARA EJECUTARSE LUEGO EN EL SERVIDOR.
